### ISSUE TITLE
Pertes de communication / Instabilités

### ISSUE THREAD

**Issue by bforest** [doudz/jeedom-plugin-zigate#11]
Bonjour,

J'utilise votre plugin depuis quelques jours et je rencontre pas mal de difficultés entre la zigate et mes modules (j'ai 5 modules Xiaomi Aqara : 1 détecteur de mouvement, 1 bouton, 1 capteur d'ouverture et 2 capteurs de température).

Aujourd'hui je constate que ca fait deux jours que mes modules ne communiquent plus avec Jeedom.
Impossible d'inclure le module "détecteur de mouvement" même après avoir fait un "Reset Zigate" et plusieurs "Synchroniser".

Une idée ? Est-ce que ca peut venir directement de ma Zigate ?
Mon plugin Zigate est à jour (ainsi que le firmware de la Zigate) et les dépendances ont été relancées ce matin.

A toutes fins utiles, les logs :
```
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File "/usr/lib/python3.4/threading.py", line 868, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.4/dist-packages/zigate/transport.py", line 53, in listen
data = self.serial.read(self.serial.in_waiting)
File "/usr/local/lib/python3.4/dist-packages/serial/serialposix.py", line 467, in in_waiting
s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
[2018-03-14 11:58:22][ERROR][zigate] : No response after command 0x0042
[2018-03-14 11:58:25][ERROR][zigate] : No response after command 0x0045
[2018-03-14 13:03:54][ERROR][zigate] : No response after command 0x0042
[2018-03-14 13:03:57][ERROR][zigate] : No response after command 0x0045
[2018-03-16 07:52:06][ERROR][zigate] : Command 0x0026 failed Failed (ZigBee event codes) 169 : b''
[2018-03-16 07:57:53][ERROR][zigate] : Bad length 5 != 42 : b'\x00\x00\x00\x11\x00\xff\x01\x80\x03\x00\x1e\x9b\x01\x01\x04\x00\x00\x00\x01\x00\x03\x00\x04\x00\x05\x00\x06\x00\x08\x00\x19\x01\x01\x10\x00\x03\x00\x02\x01\x02\x04'
[2018-03-16 07:57:55][ERROR][zigate] : No response after command 0x0011
[2018-03-16 08:03:05][ERROR][zigate] : Command 0x0026 failed Failed (ZigBee event codes) 169 : b''
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File "/usr/lib/python3.4/threading.py", line 868, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.4/dist-packages/zigate/transport.py", line 53, in listen
data = self.serial.read(self.serial.in_waiting)
File "/usr/local/lib/python3.4/dist-packages/serial/serialposix.py", line 467, in in_waiting
s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
[2018-03-16 08:19:51][ERROR][zigate] : No response after command 0x0049

```

Cordialement.

**Comment by doudz** [comment]
D'après ce que je vois c'est un problème de communication, il faudrait essayer d'arrêter le démon, débrancher et rebrancher la zigate puis relancer le démon.

Il faut aussi faire attention de ne pas utiliser la clé depuis un autre plugin ou un autre logiciel en même temps

**Comment by bforest** [comment]
Merci pour votre retour.

J'ai déjà relancé plusieurs fois le démon et débranché/rebranché la Zigate.
La Zigate est uniquement utilisée par votre plugin sur Jeedom.

J'ai passé la valeur "Port clé ZiGate" en Auto car j'ai remarqué que la clé semble changer régulièrement d’identifiant USB (ttyUSB2/ttyUSB4).

La clé est branchée directement sur une Jeedom Smart, les 4 ports USB sont utilisés (RFXCom, TéléInfo, clé Bluetooth (BLEA) et Zigate).
Je me demande s'il ne faut pas que j’investisse dans un HUB USB alimenté électriquement (j'ai lu que cela pouvait potentiellement avoir un impact sur la Zigate), un avis la dessus ?

Merci.

**Comment by doudz** [comment]
Aucune idée concernant la consommation électrique, mais tout est possible.

Comme vous avez plusieurs périphériques connecté, il est possible que le mode Auto se trompe de port et tente de communiquer avec autre chose que la zigate.

Est-ce que ça fonctionne en sélectionnant manuellement le bon port USB ?
Si la réponse est oui alors c'est que le mode Auto se trompe de port, si tel est le cas j'affinerai la recherche.

**Comment by doudz** [comment]
j'ai regardé rapidement et je pense que le problème vient du mode Auto
Actuellement le plugin cherche simplement un périphérique usb utilisant le driver pl2303
mais le problème c'est que RFXCOM et Téléinfo utilise aussi ce driver...

Merci de me confirmer que ça fonctionne en sélectionnant manuellement le bon port

**Comment by bforest** [comment]
Je me suis rendu compte du changement de port quand j'étais en mode manuellement justement.

Initialement la Zigate était détectée sur le port ttyUSB2.
Après quelques heures, je m'étais rendu compte que les modules ne communiquaient plus.
En retournant dans la configuration du plugin, le paramètre "Port clé ZiGate" était vide.
Il a fallu que je re-sélectionne la Zigate qui cette fois ci était identifiée sur le port ttyUSB4.

Le fait de sélectionner le mode Auto me permet de ne plus avoir le paramètre "Port clé ZiGate" vide.

**Comment by doudz** [comment]
Si le paramètre "Port clé ZiGate" est vide cela veut dire que le port a disparu et donc que la clé s'est déconnecté
Si physiquement vous n'avez pas débrancher la clé alors oui je penche pour un problème d'alimentation insuffisante qui provoque un reset des port USB

**Comment by bforest** [comment]
Je suis en train de voir que j'utilise le mode Auto à la fois sur le plugin Zigate et le plugin RFXCom.

Je viens de spécifier les ports USB sur les deux modules, je vais voir si cela fonctionne mieux à présent.

**Comment by bforest** [comment]
Bon ce n'est pas mieux, j'ai un problème avec la reconnaissance des ports USB.
Voici ce qui est listé à 5 mins d'intervalle :

![jeedom_usb](https://user-images.githubusercontent.com/2580135/37513733-242e5b7a-2906-11e8-95f5-ac27913b994b.png)
![jeedom_usb_2](https://user-images.githubusercontent.com/2580135/37513734-244e79be-2906-11e8-8afa-7f8ed67484c0.png)

**Comment by doudz** [comment]
Bizarre effectivement, soit c'est le port USB qui déconne la clé
soit c'est la clé qui se déconnecte et reconnecte
peut être un pb d'alimentation ou un pb avec l'adapteur usb de la zigate.

Il faudrait essayer d'enlever les autres périphériques usb pour voir si c'est un pb d'alimentation
si le problème persiste alors il faudrait vous rapprocher de zigate.fr pour faire remplacer le module USB TTL

**Comment by doudz** [comment]
J'ai modifié les dépendances pour améliorer le fonctionnement du mode Auto.
Je vous invite à relancer l'installation des dépendances.

Toutefois attention, le problème semble indiquer que la clé se déconnecte et se reconnecte à une autre adresse. Actuellement le plugin ne s'est pas se reconnecter tout seul, il faut relancer le démon manuellement (Jeedom peut le faire automatiquement aussi)

**Comment by doudz** [comment]
Corrigé

**Comment by bforest** [comment]
Pour information, après l'achat d'un hub USB alimenté électriquement semble améliorer la stabilité de mon installation.

Cependant, je constate plusieurs comportements étranges, je ne sais pas s'il faut ouvrir un autre ticket ou s'il faut que je détaille ici.
Exemple : mon détecteur d'ouverture retourne en permanence 1, impossible de faire reconnaitre mon bouton aqara (il est détecté mais l'image du module n'est pas celle d'un bouton mais l'image Zigate), le clic sur le bouton du bouton n'est pas détecter en temps réel, il faut cliquer sur le bouton "Synchroniser" pour avoir une trace d'un événement, ...

Je termine par une question bête, est-il possible d'exclure un module pour refaire une inclusion ?

Merci.

**Comment by bforest** [comment]
Désolé pour le dérangement, j'ai fini par réussir à inclure à nouveau correctement mon bouton.

La communication semble enfin se faire correctement avec 4 de mes modules (capteurs température, détecteur de mouvements et bouton).

Il reste le détecteur d'ouverture qui ne semble plus vouloir communiquer avec la Zigate mais je devrais pouvoir corriger ca rapidement.

Merci pour votre travail.

**Comment by doudz** [comment]
Merci pour le retour.
N'hésitez pas à rouvrir le ticket si les problèmes revenaient.

Pour information, pour exclure un équipement il suffit de le supprimer de Jeedom mais il y a un bug au niveau de la zigate à ce niveau là
voir https://github.com/fairecasoimeme/ZiGate/issues/29

Mais s'il s'agit de ré-inclure un équipement alors il suffit de relancer l'inclusion et de faire un appui long sur le bouton d'appairage de l'équipement, celui-ci va alors automatiquement quitter le réseau puis revenir avec une nouvelle adresse.
