### ISSUE TITLE
Problème lors de l'ajout d'un contact de porte.

### ISSUE THREAD

**Issue by seb19270** [doudz/jeedom-plugin-zigate#17]
Bonjour,

Voici mon problème : lorsque j'ajoute un contact de porte lumi.sensor_magnet.aq2 , je n'ai pas l'action onoff qui est présente.

Avez-vous déjà rencontré ce problème et si oui comment le résoudre

Merci 

Sébastien

**Comment by doudz** [comment]
Bonjour,
Je n'ai pas ce problème, mais il faut savoir que l'action n’apparaîtra qu'après avoir manœuvré le contact.
Si ça ne suffit pas il faudra peut-être cliquer sur le bouton rafraichir l'équipement

**Comment by doudz** [comment]
Si ça ne marche pas, il me faudrait les log en mode debug

**Comment by seb19270** [comment]
Merci de la réponse. J'avais essayé de rafraîchir l'équipement mais je n'avais pas ouvert le contact. Je viens d'essayer et là miracle l'action apparaît.

En tout cas merci pour la rapidité de la réponse et pour le plugin.

Bonne soirée

Sébastien
