### ISSUE TITLE
Problème lors de l'ajout d'un capteur inondation Xiaomi

### ISSUE THREAD

**Issue by tornlouses** [doudz/jeedom-plugin-zigate#19]
Bonjour,

Voici mon problème : sur les détecteurs d'inondation Xiaomi (Ils sont de type "lumi.sensor_wleak.aq1"). Je les ai synchronisés mais je n'ai que 3 commandes :

-  application_version
-  battery
-  type

Mais du coup je pense qu'il me manque une commande on/off comme sur les capteurs d'ouverture... je me trompe?
Mais on ne peut pas en ajouter.

Comme expliqué dans cet Issues : https://github.com/doudz/jeedom-plugin-zigate/issues/17 j'ai essayé de mettre le capteur dans l'eau, de synchronisé manuellement depuis le capteur, rien n'y fait je n'ai pas de commande onoff qui me remonte l'info... je vais ouvrir une nouvelle Issue.

Avez-vous déjà rencontré ce problème et si oui comment le résoudre?

Merci.

Romain.

**Comment by doudz** [comment]
Oui effectivement, ce capteur utilise un signal d'alarme qui n'est pas bien géré actuellement.
C'est aussi le cas des détecteurs de fumée par exemple.

J'espère pouvoir corriger ça prochainement.
J'ai reçu ce même capteur d'inondation récemment, je vais pouvoir faire des tests.

**Comment by tornlouses** [comment]
Top merci.
Je vais suivre ça :)

Bon courage et si je peux aider...

**Comment by doudz** [comment]
J'ai une liste des équipements utilisables, il faut juste que je prenne le temps d'écrire la documentation

**Comment by tornlouses** [comment]
Ok très bien.
Hâte d'en apprendre plus.

En avance, le xiaomi cube et les boutons xiaomi (carré) sont supportés?

**Comment by doudz** [comment]
voir https://github.com/doudz/zigate/issues/11

**Comment by doudz** [comment]
Corrigé dans la prochaine version
