### ISSUE TITLE
Plus d'information sur des capteurs d'ouverture Xiaomi

### ISSUE THREAD

**Issue by tornlouses** [doudz/jeedom-plugin-zigate#20]
Bonjour,

Après 11 jours d'utilisation avec :

- 6 capteurs d'ouverture Xiaomi
- 4 capteurs de mouvement Xiaomi
- 7 capteurs de température Xiaomi
- 2 boutons carrés Xiaomi (non fonctionnels mais associés)
- 4 capteur d'inondation Xiaomi (non fonctionnels mais associés)

Ça a bien tourné pour tous pendant 6 jours, mais depuis 5 jours je n'ai plus d'informations de deux capteurs d'ouverture...
Est-ce normal? Est-ce déjà arrivé?
Que puis-je faire pour qu'il donne de nouveau les informations d'ouverture?

Merci d'avance.
Cordialement.

**Comment by doudz** [comment]
Ce n'est pas normal, et c'est déjà arrivé à certains, surtout avec des équipements Xiaomi, il semblerait que par moment la zigate perd des équipements.
Le prochain firmware devrait résoudre le problème, j'espère

**Comment by bforest** [comment]
Juste pour information, j'ai le même comportement.

Au bout de plusieurs jours, un bouton Xiaomi et un capteur découverte Xiaomi ne communiquent plus avec la zigate.

Bilan, après un refresh, les modules sont perdus, il faut refaire une inclusion pour qu'ils soient à nouveau dispos.

Cordialement.

**Comment by tornlouses** [comment]
doudz tu as des liens qui parlent de ça pour le nouveau firmware?
J'ai cherché rapidement j'ai pas trouvé d'infos la dessus?

**Comment by doudz** [comment]
Voir https://github.com/fairecasoimeme/ZiGate/issues/38

**Comment by tornlouses** [comment]
Ok merci pour le lien.
J'espère aussi que ça sera corrigé avec le nouveau firmware!

**Comment by doudz** [comment]
Je cloture le ticket puisque ce n'est pas un problème lié au plugin.
