### ISSUE TITLE
Bouton poussoir carré Xiaomi non fonctionnel

### ISSUE THREAD

**Issue by tornlouses** [doudz/jeedom-plugin-zigate#21]
Bonjour,

Après 11 jours d'utilisation avec :

    6 capteurs d'ouverture Xiaomi
    4 capteurs de mouvement Xiaomi
    7 capteurs de température Xiaomi
    2 boutons carrés Xiaomi (non fonctionnels mais associés)
    4 capteur d'inondation Xiaomi (non fonctionnels mais associés)

Mes deux boutons poussoirs Xiaomi (comme présentés ici : **https://faire-ca-soi-meme.fr/test/2017/05/29/nouvelle-gamme-xiaomi-aqara/**) se sont bien associés dés le début mais lorsque je clique il ne change pas d'état et reste en on.
J'ai bien les commandes "application_version", "onoff", "battery" et "type".

Est-ce normal? Comment faire pour avoir deux états dessus?

Merci d'avance.
Cordialement.

**Comment by doudz** [comment]
Il est probable que les commandes manquantes apparaissent à l'utilisation du bouton

**Comment by doudz** [comment]
Je pense que le bouton n'est plus associé à la zigate, d'où le problème, je cloturerai l'issue si c'est le cas
