### ISSUE TITLE
Installation du plugin impossible

### ISSUE THREAD

**Issue by tornlouses** [doudz/jeedom-plugin-zigate#23]
Bonjour,

Je n'arrive plus à l'installer sur jeedom.
Que se passe-t-il?

Cordialement.

**Comment by doudz** [comment]
C'est un petit problème temporaire suite à la mise en ligne des sources sur github. Je règle le pb cet après midi.

**Comment by doudz** [comment]
Je n'arrête pas le développement, mais pour ma part il se fera au ralenti car je souhaiterai maintenant faire un plugin zigate pour Home assistant que j'utilise au quotidien (je n'utilise pas jeedom).
Par la même occasion le plugin devient gratuit effectivement, et j'accepterai les contributions qui se présenteront.

**Comment by doudz** [comment]
Le problème est normalement résolu

**Comment by tornlouses** [comment]
ça fonctionne l'installation.
Merci beaucoup.
