### ISSUE TITLE
Questions pour faire la documentation

### ISSUE THREAD

**Issue by Karreg** [doudz/jeedom-plugin-zigate#34]
Hello doudz,

Je travaille sur la doc du plugin à merger dans le projet, et j'ai quelques questions sur certaines fonctions, car je n'ai pas trouvé par l'expérience. Peux-tu clarifier ces questions ? Merci !

# Boutons du plugin

* TouchLink : kesako ?
* Network scan : kesako ?
* Synchroniser : Qu'est-ce que ça fait ?
* Reset ZiGate : Quelle est la portée du reset ? (suppression de conf ? suppression des équipements ? corruption des scénarios avec équipements supprimés ?)

# Bouton de l'équipement

* Identifier : Qu'est-ce qui est identifié exactement ? les commandes ? comment sont-elles trouvées ? Depuis l'équipement ou depuis une base de données ? locale ou distante ? combien de temps pour la reconnaissance ? comment voir les modifications ? j'ai constaté que je devais attendre un certain temps, et rafraîchir plein de fois le navigateur, et le résultat était aussi très aléatoire...
* Rafraîchir l'équipement : Qu'est-ce que ça fait exactement ? Dans quel cas c'est demandé par le plugin (via les notifs ?)

# Paramètres de l'équipement

* ADDR : Adresse de l'équipement dans le réseau ZigBee ?
* IEEE : identifiant de l'équipement, ou du modèle ?
* Link quality : quelles sont les valeurs "normales" d'un link de bonne qualité ?
* Power source : la valeur n'est pas forcément bonne, mon ampoule Ikea est de valeur 0, donc théoriquement sur batterie alors que c'est sur secteur

**Comment by doudz** [comment]
Salut Karreg, 
Merci beaucoup pour ton implication.

Voici les réponse à tes questions :

###  Boutons du plugin
- TouchLink : ça permet de faire une association avec la fonction Touchlink, c'est par exemple la méthode utilisée par la télécommande Ikea pour s'associer avec une ampoule
- Network scan : Bonne question, ça lance un scan network du réseau Zigbee, dans certains cas c'est nécessaire pour appairer un équipement mais je ne l'ai jamais utilisé
- Synchroniser : En réalité c'est le démon qui gère les équipements associés à la zigate, ce bouton sert à synchroniser Jeedom et le démon, ajouter/supprimer/modifier les objets Jeedom pour correspondre à la vision du démon.
- Reset ZiGate : ça fait simplement un redémarrage de la zigate. Rien n'est perdu, pour moi c'est équivalent à un débranchement/rebranchement
Il existe une autre fonction appelé Factory Reset, qui permet de revenir à la configuration d'usine de la zigate, mais je n'ai pas mis d'accès dans Jeedom

### Bouton de l'équipement
- Identifier : ça lance la commande Identify pour 5 secondes, le résultat dépend de l'équipement, typiquement pour une ampoule, ça la fait clignoter, ça permet de l'identifier physiquement
- Rafraîchir l'équipement : cette commande est assez importante, elle lance une série de question à l'équipement afin de découvrir ses capacités et ainsi le configurer correctement. Cette opération est faite automatiquement lorsqu'on associe un équipement. Parfois il peut être utile de relancer la commande, par exemple lorsqu'une ampoule IKEA ne transmet plus son état, ça permet de rétablir la demande de reporting. 
Le plugin identifie lorsqu'il faut faire un rafraichissement. Lorsqu'il s'agit d'un équipement sur secteur, une ampoule par exemple, le rafraichissement se fait automatiquement sans rien dire. Lorsqu'il s'agit d'un équipement sur batterie, une sonde Xiaomi par exemple, il faut appuyer une ou plusieurs fois sur le bouton d'appairage de la sonde afin qu'elle réponde aux questions envoyées.
Cette vérification automatique est faite uniquement au démarrage du démon.

### Paramètres de l'équipement
- ADDR : Adresse de l'équipement dans le réseau ZigBee, oui
- IEEE : c'est l'adresse uniquement de l'équipement, comme une adresse MAC
- Link quality : c'est la valeur RSSI du dernier message reçu, qui varie de 0 à 255, ça indique la puissance du signale reçu
- Power source : en fait 0 veut dire inconnu, 3 veut dire sur batterie, je pense qu'il faudrait enlever cette information, elle n'apporte rien au plugin.

**Comment by Karreg** [comment]
Merci pour les réponses. Quelles précisions :

# Boutons du plugin

* Touchlink : j'en déduis que pour ajouter un bouton Ikea, il faut cliquer sur "TouchLink" et non "Mode inclusion" ? J'ai du mal à saisir la différence concrètement

# Boutons de l'équipement

Ces réponses sont en or, je pense qu'il y a un réel écart entre ce que semble signifier les boutons, et ce qu'ils font vraiment. Pour moi le rafraichissement, c'est ce que devrait faire identifier. Comme quoi c'est utile de faire la doc ;)

# Paramètres de l'équipement

* Link Quality : une idée de la valeur "dans la norme" ? Histoire de donner une valeur indicative à partir de laquelle on peut considérer que le lien est trop faible pour être fiable
* Power source : je trouve au contraire que ça peut être utile. rarement, mais utile quand même, pour analyser certains cas. Par contre le label dans le plugin ne donne pas les bonnes valeurs.

Je mets à jour la doc avec les autres réponses.

**Comment by Karreg** [comment]
Premier jet de la doc effectué, dès que j'ai les précisions ci-dessus je te transmets une MR :)

**Comment by doudz** [comment]
Pour le Touchlink, honnêtement je ne connais pas la procédure. Je pense qu'il faut rester vague pour le moment et simplement indiquer que cela permet de faire une association avec la technologie Touchlink, sans préciser Ikea ou autre.

Pour le link quality, je n'ai pas de valeur, simplement plus la valeur est faible, plus il y a de chance que le signal ne soit pas capté. Sur mon installation, le plus faible est à 51 mais c'est aussi cet équipement qui disparait par moment...

Merci pour la doc, c'est un travail fastidieux mais utile

**Comment by Karreg** [comment]
Ce n'est qu'un premier jet. Je n'ai que quelques équipement Ikea donc la partie Xiaomi et Philips je ne pourrai pas les remplir. Je le ferai en best effort si je vois des choses sur le forum.
Mais au moins la structure est en place, ainsi que la doc du plugin.

Done dans la MR #35
