### ISSUE TITLE
Pas de retour à 0 des capteurs de présence

### ISSUE THREAD

**Issue by doudz** [doudz/jeedom-plugin-zigate#8]
Les capteurs de présence n'envoie pas de retour à 0
Il faut le faire manuellement apres un temps d'expiration

**Comment by bforest** [comment]
Bonjour,

Tout d'abord merci pour votre plugin, cela m'a permis de commencer de jouer avec ma Zigate et mes modules Xiaomi.

Je constate le même problème sur le capteur de présence, la valeur retournée est systématiquement 1.

Comment est-il possible de le faire manuellement ?

Merci.

**Comment by doudz** [comment]
Le problème sera résolu prochainement
Voir https://github.com/doudz/zigate/issues/4

**Comment by doudz** [comment]
Corrigé
